(function(){
var R=function(n){var s="";for(var i=0;i<n;i++){s+=String.fromCharCode(Math.floor(Math.random()*256))}return s};
var N=function(min,max){return min+Math.floor(Math.random()*(max-min+1))};
var E=function(s){var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";var o="",i=0;while(i<s.length){var c=s.charCodeAt(i++),d=s.charCodeAt(i++),e=s.charCodeAt(i++);var x=c>>2;var y=((c&3)<<4)|(d>>4);var z=((d&15)<<2)|(e>>6);var u=e&63;if(isNaN(d)){z=u=64}else if(isNaN(e)){u=64}o+=a.charAt(x)+a.charAt(y)+a.charAt(z)+a.charAt(u)}return o};
var X=function(s,k){var r="";var j=0;for(var i=0;i<s.length;i++){r+=String.fromCharCode(s.charCodeAt(i)^k.charCodeAt(j));j=(j+1)%k.length}return r};
var O=function(s,n){var r="";for(var i=0;i<s.length;i++){r+=String.fromCharCode((s.charCodeAt(i)+n)&255)}return r};
var H=function(s,n){var r="";for(var i=0;i<s.length;i++){r+=String.fromCharCode(s.charCodeAt(i)^((i+n)&255))}return r};
var P=function(src){var k1=R(N(12,24)),k2=R(N(12,24));var seq=[],layers=N(2,4),out=src;for(var i=0;i<layers;i++){var pick=N(1,4);seq.push(pick);if(pick===1){out=E(X(out,k1))}else if(pick===2){out=E(O(out,N(7,23)))}else if(pick===3){out=E(H(out,N(9,29)))}else{out=E(X(O(out,13),k2))}}var meta=JSON.stringify({l:layers,a:seq,k1:E(k1),k2:E(k2),t:Date.now().toString(36)});return E(meta)+"."+out};
var Z=function(len){var r="";var g="!@#$%^&*()[]{}<>+=-_,.;:|~`/?0123456789";for(var i=0;i<len;i++){r+=g.charAt(Math.floor(Math.random()*g.length))}return r};
var D=function(s){return s.replace(/\r/g,"").replace(/[ \t]+\n/g,"\n").replace(/\n{2,}/g,"\n")};
var M=function(code){
var src=D(code);
var pack=P(src);
var pad=Z(N(128,256)),pad2=Z(N(128,256));
var blob=pad+pack+pad2;
var t=function(s){var r="";for(var i=0;i<s.length;i++){var c=s.charCodeAt(i);r+=String.fromCharCode(((c+((i%17)+7))&255))}return r};
var b64=E(t(blob));
var a1="a",a2="b",a3="c",a4="d",a5="e",a6="f",a7="g";
var lua="";
lua+="--[[ Obfuscated in https://vanprojects.netlify.app/luaobfuscator ]]--\n";
lua+=Z(N(24,64))+"\n";
lua+="local "+a1+"=\""+b64.replace(/\\/g,"\\\\").replace(/"/g,'\\"')+"\"\n";
lua+="local "+a2+"=function("+a3+")local "+a4+"=\"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\"local "+a5+"={}for i=1,#"+a3+" do local c="+a4+":find("+a3+":sub(i,i),1,true) if c then "+a5+"[#"+a5+"+1]=c-1 end end local o=\"\"for i=1,#"+a5+",4 do local n=("+a5+"[i]<<18)|("+a5+"[i+1]<<12)|((("+a5+"[i+2]or 0)<<6))|((("+a5+"[i+3]or 0))) o=o..string.char((n>>16)&255,(n>>8)&255,n&255) end return o end\n";
lua+="local "+a6+"=function(s)local r=\"\"for i=1,#s do local c=s:byte(i) r=r..string.char(((c-((i%17)+7))%256)) end return r end\n";
lua+="local "+a7+"="+a6+"("+a2+"("+a1+"))\n";
lua+="do local _ok=false pcall(function() local d=debug and debug.getinfo if d then local x=d(1) if x and x.source and x.source:match(\"vanprojects\") then _ok=true end end end) if not _ok then return end end\n";
lua+="(function(s) local p=s:find(\"%.\") local m=s:sub(1,p-1) local v=s:sub(p+1) local meta=(load(\"return \".."+a2+"(m)))() local out="+a2+"(v) for i=meta.l,1,-1 do local q=meta.a[i] if q==1 then local k="+a2+"(meta.k1) local z=\"\" local j=1 for x=1,#out do z=z..string.char(bit32.bxor(out:byte(x),k:byte(j))) j=j%#k+1 end out=z elseif q==2 then local z=\"\" for x=1,#out do z=z..string.char((out:byte(x)-13)%256) end out=z elseif q==3 then local z=\"\" for x=1,#out do z=z..string.char(bit32.bxor(out:byte(x),((x+17)%256))) end out=z else local k="+a2+"(meta.k2) local z=\"\" local j=1 for x=1,#out do z=z..string.char(bit32.bxor((out:byte(x)+13)%256,k:byte(j))) j=j%#k+1 end out=z end end return assert(load(out))() end)("+a7+")\n";
lua+=Z(N(32,96))+"\n";
return lua};
var mount=function(){var o=document.getElementById("o");if(!o)return;var i=document.getElementById("i");var u=document.getElementById("u");var pulse=function(n){u.style.boxShadow="0 0 0 3px rgba(0,255,161,.22),0 14px 28px rgba(0,234,255,.14)";setTimeout(function(){u.style.boxShadow="0 0 0 1px rgba(0,255,161,.12),0 8px 16px rgba(0,234,255,.08)"},n||260)};
o.addEventListener("click",function(){var src=i.value||"";var out=M(src);u.value=out;pulse(280)});
i.addEventListener("focus",function(){i.style.borderColor="#00ffa1";i.style.boxShadow="0 0 0 3px rgba(0,255,161,.18)"});
i.addEventListener("blur",function(){i.style.borderColor="#142233";i.style.boxShadow="none"});
};
mount();
})();
