(function(){
var S=function(n){var a=new Uint8Array(n);for(var i=0;i<n;i++){a[i]=Math.floor(Math.random()*256)}var s="";for(var j=0;j<n;j++){s+=String.fromCharCode(a[j])}return s};
var R=function(){var t=Date.now().toString(36);var r=(Math.random()+"").slice(2);return t+r+S(16)};
var B64E=function(s){var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";var o="";var i=0;while(i<s.length){var c=s.charCodeAt(i++),d=s.charCodeAt(i++),e=s.charCodeAt(i++);var x=c>>2;var y=((c&3)<<4)|(d>>4);var z=((d&15)<<2)|(e>>6);var u=e&63;if(isNaN(d)){z=u=64}else if(isNaN(e)){u=64}o+=a.charAt(x)+a.charAt(y)+a.charAt(z)+a.charAt(u)}return o};
var B64D=function(s){var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";var o="",i=0,c,d,e,p=[0,0,0,0];while(i<s.length){p[0]=a.indexOf(s.charAt(i++));p[1]=a.indexOf(s.charAt(i++));p[2]=a.indexOf(s.charAt(i++));p[3]=a.indexOf(s.charAt(i++));c=(p[0]<<2)|(p[1]>>4);d=((p[1]&15)<<4)|(p[2]>>2);e=((p[2]&3)<<6)|p[3];o+=String.fromCharCode(c);if(p[2]!==64){o+=String.fromCharCode(d)}if(p[3]!==64){o+=String.fromCharCode(e)}}return o};
var XOR=function(s,k){var r="";var j=0;for(var i=0;i<s.length;i++){r+=String.fromCharCode(s.charCodeAt(i)^k.charCodeAt(j));j=(j+1)%k.length}return r};
var ROT=function(s,n){var r="";for(var i=0;i<s.length;i++){r+=String.fromCharCode((s.charCodeAt(i)+n)&255)}return r};
var SHF=function(s,n){var r="";for(var i=0;i<s.length;i++){r+=String.fromCharCode((s.charCodeAt(i)^((i+n)&255)))}return r};
var RND=function(min,max){return min+Math.floor(Math.random()*(max-min+1))};
var PK=function(src){var k1=S(RND(12,24)),k2=S(RND(12,24)),k3=S(RND(8,16));var seq=[];var layers=RND(2,4);var out=src;for(var i=0;i<layers;i++){var pick=RND(1,4);seq.push(pick);if(pick===1){out=B64E(XOR(out,k1))}else if(pick===2){out=B64E(ROT(out,RND(5,19)))}else if(pick===3){out=B64E(SHF(out,RND(7,23)))}else{out=B64E(XOR(ROT(out,13),k2))}}
var meta=JSON.stringify({l:layers,a:seq,k1:B64E(k1),k2:B64E(k2),k3:B64E(k3),s:R()});
return B64E(meta)+"."+out};
var MIN=function(s){return s.replace(/\r/g,"").replace(/[ \t]+\n/g,"\n").replace(/\n{2,}/g,"\n")};
var CF=function(s){var blocks=[];var cur="";for(var i=0;i<s.length;i++){cur+=s[i];if(cur.length>96&&Math.random()<0.07){blocks.push(cur);cur=""}}if(cur.length>0){blocks.push(cur)}var tbl=[];for(var j=0;j<blocks.length;j++){tbl.push(blocks[j])}
var out="";for(var k=0;k<tbl.length;k++){out+=tbl[k]}return out};
var RNDID=function(len){var r="";for(var i=0;i<len;i++){r+=String.fromCharCode(97+Math.floor(Math.random()*26))}return r};
var MAKE=function(code){
var src=MIN(code);
var packed=PK(src);
var glyphs="!@#$%^&*()[]{}<>+=-_,.;:|~`/?0123456789";
var pad=function(n){var s="";for(var i=0;i<n;i++){s+=glyphs.charAt(Math.floor(Math.random()*glyphs.length))}return s};
var blob=pad(RND(64,128))+packed+pad(RND(64,128));
var t=function(s){var r="";for(var i=0;i<s.length;i++){var c=s.charCodeAt(i);r+=String.fromCharCode(((c+((i%11)+5))&255))}return r};
var b=t(blob);
var b64=B64E(b);
var dA=RNDID(RND(2,3)),dB=RNDID(RND(2,3)),dC=RNDID(RND(2,3)),dD=RNDID(RND(2,3)),dE=RNDID(RND(2,3)),dF=RNDID(RND(2,3));
var lua="";
lua+="--[[ Obfuscated in https://vanprojects.netlify.app/luaobfuscator ]]--\n";
lua+=pad(RND(12,32))+"\n";
lua+="local "+dA+"=\""+b64.replace(/\\/g,"\\\\").replace(/"/g,'\\"')+"\"\n";
lua+="local "+dB+"=function("+dC+")local "+dD+"=\"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\"local "+dE+"={}for i=1,#"+dC+" do local c="+dD+":find("+dC+":sub(i,i),1,true) if c then "+dE+"[#"+dE+"+1]=c-1 end end local o=\"\"for i=1,#"+dE+",4 do local n=("+dE+"[i]<<18)|("+dE+"[i+1]<<12)|((("+dE+"[i+2]or 0)<<6))|((("+dE+"[i+3]or 0))) o=o..string.char((n>>16)&255,(n>>8)&255,n&255) end return o end\n";
lua+="local "+dF+"=function(s)local r=\"\"for i=1,#s do local c=s:byte(i) r=r..string.char(((c-((i%11)+5))%256)) end return r end\n";
lua+="local _=((function(x)return x end))("+dF+"("+dB+"("+dA+")))\n";
lua+="local __=((function(x)return x end))(_)\n";
lua+="local ___=(function(x)return x end)(__)\n";
lua+="local ____=(function(x)return x end)(___)\n";
lua+="local ______=(function(x)return x end)(____)\n";
lua+="local _______=(function(x)return x end)(______) \n";
lua+="local ________=((function(s)local p=s:find(\"%.\") local m=s:sub(1,p-1) local v=s:sub(p+1) local meta=(load(\"return \".."+dB+"(m)))() local out="+dB+"(v) for i=meta.l,1,-1 do local pick=meta.a[i] if pick==1 then local k="+dB+"(meta.k1) local z=\"\" local j=1 for x=1,#out do z=z..string.char(bit32.bxor(out:byte(x),k:byte(j))) j=j%#k+1 end out=z elseif pick==2 then local z=\"\" for x=1,#out do z=z..string.char((out:byte(x)-"+RND(5,19)+")%256) end out=z elseif pick==3 then local z=\"\" for x=1,#out do z=z..string.char(bit32.bxor(out:byte(x),((x+"+RND(7,23)+")%256))) end out=z else local k="+dB+"(meta.k2) local z=\"\" local j=1 for x=1,#out do z=z..string.char(bit32.bxor((out:byte(x)+13)%256,k:byte(j))) j=j%#k+1 end out=z end end return out end))(_______)\n";
lua+="local __________=(function(b)return load(b) end)(__________)\n";
lua+="do local __ok=false pcall(function() local d=debug and debug.getinfo if d then local x=d(1) if x and x.source and x.source:match(\"vanprojects\") then __ok=true end end end) if not __ok then error(\"Tampering detected\") end end\n";
lua+="(function(f)return f() end)(function() return assert(load(______))() end)\n";
lua+=pad(RND(24,48))+"\n";
lua+=CF("");
return lua};
var mount=function(){var o=document.getElementById("o");if(!o)return;var i=document.getElementById("i");var u=document.getElementById("u");var pulse=function(n){u.style.boxShadow="0 0 0 3px rgba(0,255,161,.2),0 12px 24px rgba(0,234,255,.12)";setTimeout(function(){u.style.boxShadow="0 0 0 1px rgba(0,255,161,.12),0 8px 16px rgba(0,234,255,.08)"},n||240)};
o.addEventListener("click",function(){var src=i.value||"";var out=MAKE(src);u.value=out;pulse(260)});
i.addEventListener("focus",function(){i.style.borderColor="#00ffa1";i.style.boxShadow="0 0 0 3px rgba(0,255,161,.18)"});
i.addEventListener("blur",function(){i.style.borderColor="#142233";i.style.boxShadow="none"});
};
mount();
})();
